
0 0 at *TIMELINE named UNTITLED.TL { $2 attr ! 0 tio !  
    0 0 at *KEYFRAME {  
        5 14 at *TILE { 0. 0. hx v! 16. 16. w v! 21 ti !  } 
        10 -27 at *TILE { 0. 0. hx v! 16. 16. w v! 21 ti !  } 
        -20 -40 at *TILE { 0. 0. hx v! 16. 16. w v! 21 ti !  } 
        -41 4 at *TILE { 0. 0. hx v! 16. 16. w v! 21 ti !  } 
        -19 32 at *TILE { 0. 0. hx v! 16. 16. w v! 21 ti !  } 
    } 
} 